package com.group_finity.mascot.environment.home;

import com.group_finity.mascot.Main;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class DebugWindowNew extends JFrame {
    private JLabel lblBehaviour;
    private JLabel lblBehaviourValue;
    private JLabel lblEnvironmentHeightValue;
    private JLabel lblEnvironmentWidthValue;
    private JLabel lblWindowYValue;
    private JLabel lblWindowXValue;
    private JLabel lblActiveIEValue;
    private JLabel lblShimejiYValue;
    private JLabel lblShimejiXValue;
    private JLabel lblFocusedValue;
    private JLabel lblShimejiX;
    private JLabel lblShimejiY;
    private JLabel lblActiveIE;
    private JLabel lblFocused;
    private JLabel lblWindowX;
    private JLabel lblWindowY;
    private JLabel lblEnvironmentWidth;
    private JLabel lblEnvironmentHeight;
    private JPanel contentPane;

    public void setBehaviour(String text) {
        lblBehaviourValue.setText(text);
    }

    public void setShimejiX(int x) {
        lblShimejiXValue.setText(String.format("%d", x));
    }

    public void setShimejiY(int y) {
        lblShimejiYValue.setText(String.format("%d", y));
    }

    public void setWindowTitle(String title) {
        lblActiveIEValue.setText(title);
    }

    public void setFocusedValue(String title) {
        lblFocusedValue.setText(title);
    }

    public void setWindowX(int x) {
        lblWindowXValue.setText(String.format("%d", x));
    }

    public void setWindowY(int y) {
        lblWindowYValue.setText(String.format("%d", y));
    }

    public void setEnvironmentWidth(int width) {
        lblEnvironmentWidthValue.setText(String.format("%d", width));
    }

    public void setEnvironmentHeight(int height) {
        lblEnvironmentHeightValue.setText(String.format("%d", height));
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            lblBehaviour.setText(Main.getInstance().getLanguageBundle().getString("Behaviour"));
            lblShimejiX.setText(Main.getInstance().getLanguageBundle().getString("ShimejiX"));
            lblShimejiY.setText(Main.getInstance().getLanguageBundle().getString("ShimejiY"));
            lblActiveIE.setText(Main.getInstance().getLanguageBundle().getString("ActiveIE"));
            lblWindowX.setText(Main.getInstance().getLanguageBundle().getString("WindowX"));
            lblWindowY.setText(Main.getInstance().getLanguageBundle().getString("WindowY"));
            lblEnvironmentWidth.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentWidth"));
            lblEnvironmentHeight.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentHeight"));
        }
        super.setVisible(b);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), "Stats", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lblBehaviour = new JLabel();
        lblBehaviour.setText("Behavior");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblBehaviour, gbc);
        lblBehaviourValue = new JLabel();
        lblBehaviourValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblBehaviourValue, gbc);
        lblShimejiXValue = new JLabel();
        lblShimejiXValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblShimejiXValue, gbc);
        lblShimejiYValue = new JLabel();
        lblShimejiYValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblShimejiYValue, gbc);
        lblActiveIEValue = new JLabel();
        lblActiveIEValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblActiveIEValue, gbc);
        lblShimejiX = new JLabel();
        lblShimejiX.setText("X");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblShimejiX, gbc);
        lblShimejiY = new JLabel();
        lblShimejiY.setText("Y");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblShimejiY, gbc);
        lblActiveIE = new JLabel();
        lblActiveIE.setText("Window Title");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblActiveIE, gbc);
        lblFocused = new JLabel();
        lblFocused.setText("Window Focused");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblFocused, gbc);
        lblFocusedValue = new JLabel();
        lblFocusedValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblFocusedValue, gbc);
        lblWindowX = new JLabel();
        lblWindowX.setText("Window X");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblWindowX, gbc);
        lblWindowY = new JLabel();
        lblWindowY.setText("Window Y");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblWindowY, gbc);
        lblEnvironmentWidth = new JLabel();
        lblEnvironmentWidth.setText("Environment W");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblEnvironmentWidth, gbc);
        lblEnvironmentHeight = new JLabel();
        lblEnvironmentHeight.setText("Environment H");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblEnvironmentHeight, gbc);
        lblWindowXValue = new JLabel();
        lblWindowXValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblWindowXValue, gbc);
        lblWindowYValue = new JLabel();
        lblWindowYValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblWindowYValue, gbc);
        lblEnvironmentWidthValue = new JLabel();
        lblEnvironmentWidthValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblEnvironmentWidthValue, gbc);
        lblEnvironmentHeightValue = new JLabel();
        lblEnvironmentHeightValue.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(lblEnvironmentHeightValue, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        contentPane.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
