package com.group_finity.mascot;

import javax.swing.*;

/**
 * @author Kilkakon
 */
public class DebugWindow extends JFrame {
    public DebugWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        lblShimejiX = new JLabel();
        lblShimejiXValue = new JLabel();
        lblShimejiYValue = new JLabel();
        lblShimejiY = new JLabel();
        lblWindowX = new JLabel();
        lblWindowY = new JLabel();
        lblWindowWidth = new JLabel();
        lblWindowHeight = new JLabel();
        lblWindowXValue = new JLabel();
        lblWindowYValue = new JLabel();
        lblWindowWidthValue = new JLabel();
        lblWindowHeightValue = new JLabel();
        lblBehaviour = new JLabel();
        lblBehaviourValue = new JLabel();
        lblEnvironmentY = new JLabel();
        lblEnvironmentX = new JLabel();
        lblEnvironmentXValue = new JLabel();
        lblEnvironmentYValue = new JLabel();
        lblEnvironmentWidth = new JLabel();
        lblEnvironmentHeight = new JLabel();
        lblEnvironmentHeightValue = new JLabel();
        lblEnvironmentWidthValue = new JLabel();
        lblActiveIE = new JLabel();
        lblActiveIEValue = new JLabel();
        lblFocused = new JLabel();
        lblFocusedValue = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        var contentPane = getContentPane();

        //---- lblShimejiX ----
        lblShimejiX.setText("Shimeji X");

        //---- lblShimejiXValue ----
        lblShimejiXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblShimejiXValue.setText("N/A");

        //---- lblShimejiYValue ----
        lblShimejiYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblShimejiYValue.setText("N/A");

        //---- lblShimejiY ----
        lblShimejiY.setText("Shimeji Y");

        //---- lblWindowX ----
        lblWindowX.setText("Window X");

        //---- lblWindowY ----
        lblWindowY.setText("Window Y");

        //---- lblWindowWidth ----
        lblWindowWidth.setText("Window W");

        //---- lblWindowHeight ----
        lblWindowHeight.setText("Window H");

        //---- lblWindowXValue ----
        lblWindowXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowXValue.setText("N/A");

        //---- lblWindowYValue ----
        lblWindowYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowYValue.setText("N/A");

        //---- lblWindowWidthValue ----
        lblWindowWidthValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowWidthValue.setText("N/A");

        //---- lblWindowHeightValue ----
        lblWindowHeightValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowHeightValue.setText("N/A");

        //---- lblBehaviour ----
        lblBehaviour.setText("Behaviour");

        //---- lblBehaviourValue ----
        lblBehaviourValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblBehaviourValue.setText("N/A");

        //---- lblEnvironmentY ----
        lblEnvironmentY.setText("Environment Y");

        //---- lblEnvironmentX ----
        lblEnvironmentX.setText("Environment X");

        //---- lblEnvironmentXValue ----
        lblEnvironmentXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentXValue.setText("N/A");

        //---- lblEnvironmentYValue ----
        lblEnvironmentYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentYValue.setText("N/A");

        //---- lblEnvironmentWidth ----
        lblEnvironmentWidth.setText("Environment W");

        //---- lblEnvironmentHeight ----
        lblEnvironmentHeight.setText("Environment H");

        //---- lblEnvironmentHeightValue ----
        lblEnvironmentHeightValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentHeightValue.setText("N/A");

        //---- lblEnvironmentWidthValue ----
        lblEnvironmentWidthValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentWidthValue.setText("N/A");

        //---- lblActiveIE ----
        lblActiveIE.setText("Active IE");

        //---- lblActiveIEValue ----
        lblActiveIEValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblActiveIEValue.setText("N/A");

        // ---- lblFocused ----
        lblFocused.setText("Focused");
        lblFocused.setHorizontalAlignment(SwingConstants.RIGHT);
        lblFocusedValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblFocusedValue.setText("false");


        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(lblShimejiX)
                        .addComponent(lblShimejiY)
                        .addComponent(lblBehaviour)
                        .addComponent(lblWindowX)
                        .addComponent(lblWindowY)
                        .addComponent(lblWindowWidth)
                        .addComponent(lblWindowHeight)
                        .addComponent(lblEnvironmentX)
                        .addComponent(lblEnvironmentY)
                        .addComponent(lblEnvironmentWidth)
                        .addComponent(lblEnvironmentHeight)
                        .addComponent(lblActiveIE))
                        .addComponent(lblFocused)
                    .addGap(42, 42, 42)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(lblBehaviourValue, GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(lblShimejiYValue)
                                .addComponent(lblShimejiXValue)
                                .addComponent(lblWindowXValue)
                                .addComponent(lblWindowYValue)
                                .addComponent(lblWindowHeightValue)
                                .addComponent(lblEnvironmentHeightValue)
                                .addComponent(lblEnvironmentWidthValue)
                                .addComponent(lblWindowWidthValue)
                                .addComponent(lblEnvironmentXValue)
                                .addComponent(lblEnvironmentYValue)
                                .addComponent(lblActiveIEValue))
                                .addComponent(lblFocusedValue)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBehaviour)
                        .addComponent(lblBehaviourValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFocused)
                            .addComponent(lblFocusedValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblShimejiX)
                        .addComponent(lblShimejiXValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblShimejiYValue)
                        .addComponent(lblShimejiY))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblActiveIE)
                        .addComponent(lblActiveIEValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWindowX)
                        .addComponent(lblWindowXValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWindowY)
                        .addComponent(lblWindowYValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWindowWidth)
                        .addComponent(lblWindowWidthValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(lblWindowHeight)
                        .addComponent(lblWindowHeightValue, GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(lblEnvironmentXValue)
                        .addComponent(lblEnvironmentX))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnvironmentY)
                        .addComponent(lblEnvironmentYValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnvironmentWidth)
                        .addComponent(lblEnvironmentWidthValue))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEnvironmentHeight)
                        .addComponent(lblEnvironmentHeightValue))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    void setBehaviour(String text) {
        lblBehaviourValue.setText(text);
    }

    void setShimejiX(int x) {
        lblShimejiXValue.setText(String.format("%d", x));
    }

    void setShimejiY(int y) {
        lblShimejiYValue.setText(String.format("%d", y));
    }

    void setWindowTitle(String title) {
        lblActiveIEValue.setText(title);
    }

    void setWindowX(int x) {
        lblWindowXValue.setText(String.format("%d", x));
    }

    void setWindowY(int y) {
        lblWindowYValue.setText(String.format("%d", y));
    }

    void setWindowWidth(int width) {
        lblWindowWidthValue.setText(String.format("%d", width));
    }

    void setWindowHeight(int height) {
        lblWindowHeightValue.setText(String.format("%d", height));
    }

    void setEnvironmentX(int x) {
        lblEnvironmentXValue.setText(String.format("%d", x));
    }

    void setEnvironmentY(int y) {
        lblEnvironmentYValue.setText(String.format("%d", y));
    }

    void setEnvironmentWidth(int width) {
        lblEnvironmentWidthValue.setText(String.format("%d", width));
    }

    void setEnvironmentHeight(int height) {
        lblEnvironmentHeightValue.setText(String.format("%d", height));
    }
     void setFocusedValue(String title) {
        lblFocusedValue.setText(title);
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            lblBehaviour.setText(Main.getInstance().getLanguageBundle().getString("Behaviour"));
            lblShimejiX.setText(Main.getInstance().getLanguageBundle().getString("ShimejiX"));
            lblShimejiY.setText(Main.getInstance().getLanguageBundle().getString("ShimejiY"));
            lblActiveIE.setText(Main.getInstance().getLanguageBundle().getString("ActiveIE"));
            lblWindowX.setText(Main.getInstance().getLanguageBundle().getString("WindowX"));
            lblWindowY.setText(Main.getInstance().getLanguageBundle().getString("WindowY"));
            lblWindowWidth.setText(Main.getInstance().getLanguageBundle().getString("WindowWidth"));
            lblWindowHeight.setText(Main.getInstance().getLanguageBundle().getString("WindowHeight"));
            lblEnvironmentX.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentX"));
            lblEnvironmentY.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentY"));
            lblEnvironmentWidth.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentWidth"));
            lblEnvironmentHeight.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentHeight"));
            lblFocused.setText("Focused");
        }
        super.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JLabel lblShimejiX;
    private JLabel lblShimejiXValue;
    private JLabel lblShimejiYValue;
    private JLabel lblShimejiY;
    private JLabel lblWindowX;
    private JLabel lblWindowY;
    private JLabel lblWindowWidth;
    private JLabel lblWindowHeight;
    private JLabel lblWindowXValue;
    private JLabel lblWindowYValue;
    private JLabel lblWindowWidthValue;
    private JLabel lblWindowHeightValue;
    private JLabel lblBehaviour;
    private JLabel lblBehaviourValue;
    private JLabel lblEnvironmentY;
    private JLabel lblEnvironmentX;
    private JLabel lblEnvironmentXValue;
    private JLabel lblEnvironmentYValue;
    private JLabel lblEnvironmentWidth;
    private JLabel lblEnvironmentHeight;
    private JLabel lblEnvironmentHeightValue;
    private JLabel lblEnvironmentWidthValue;
    private JLabel lblActiveIE;
    private JLabel lblActiveIEValue;
    private JLabel lblFocused;
    private JLabel lblFocusedValue;
    // End of variables declaration//GEN-END:variables
}